version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  create-reminder:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: --dev
          pkg-manager: pipenv
      - run:
          name: "create reminder"
          command: pipenv run python app.py

workflows:
  workflow:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - create-reminder
